### ISSUE TITLE
Anti Spam

### ISSUE THREAD

**Issue by partydev** [egg82/TabChat#14]
**Describe the solution you'd like**
If a user sends X messages in Y seconds, mute them for Z amount of time automatically.

**Comment by clrxbl** [comment]
"mute them for Z amount of time automatically."

Run a configurable command* Please don't ever implement some shit muting system like in VentureChat, there's have punishment plugins for that.

Should also add command cooldowns and chat message delays (how often you can send a message in chat)

**Comment by partydev** [comment]
+1 on channel cooldowns.

Configurable command is preferred. Automuting systems are nice in general IMO.
