### ISSUE TITLE
Vanish Support

### ISSUE THREAD

**Issue by partydev** [egg82/TabChat#16]
**Describe the solution you'd like**
Do not let people initiate private conversations with people who are vanished using SuperVanish or VanishNoPacket.

**Comment by clrxbl** [comment]
PremiumVanish / any popular Vanish plugin aswell

**Comment by mbax** [comment]
The fabulous news is it looks like SuperVanish (and thus by extension I assume PremiumVanish) uses my suggested (from VNP) plugin agnostic visibility check for the basic vanish state. 

Just check `player.getMetadata("vanished")` for being set, and if set, it should have a boolean true/false value.

Seems reasonable to expect this from other plugins. I remember (but can't recall the name) seeing this on other plugins too.

**Comment by clrxbl** [comment]
Tab completion also shouldn't be working for vanished players.
