### ISSUE TITLE
Overall Design Configuration

### ISSUE THREAD

**Issue by partydev** [egg82/TabChat#19]
**Describe the solution you'd like**
Allow user to define the borders, colors, etc. of the overall design of the plugin.

An example of a plugin that does something similar is quickshop. You can modify the border any any aspect in the shop.
![image](https://user-images.githubusercontent.com/42015460/74971829-b6a7e600-53ee-11ea-8180-2c7c99480a6a.png)

**Comment by clrxbl** [comment]
In my opinion, don't bother with borders at all since they're kind of a mess (especially since users don't always have the chat width at default settings).
Messaging should be 100% configurable though.

**Comment by partydev** [comment]
Borders can be icky but most players have not modified their chat width at all. I'd be interested in seeing a side by side comparison. Borders are definitely not necessary.
