### ISSUE TITLE
Announcements Channel

### ISSUE THREAD

**Issue by partydev** [egg82/TabChat#2]
**Describe the solution you'd like**
Announcement channel tab where announcements are preset messages defined in a config. The channel will be static, no messages will be sent to or from this channel. The messages will be there regardless of when you joined the server.

**Comment by egg82** [comment]
Should be solved by adding permissions for join/leave and an "is default?" boolean in the DB per channel. Chatting is solved by perms for view/chat. I don't see a reason to add announcements in a config file, but rather expose an API for other plugins and let staff chat in an announcements channel they can create by setting up the correct perms.

**Comment by partydev** [comment]
I felt a static config-based announcements channel would be easier to keep the chat in there permanently. Up to you.
