### ISSUE TITLE
DiscordSRV Support

### ISSUE THREAD

**Issue by partydev** [egg82/TabChat#22]
**Describe the solution you'd like**
DiscordSRV support, where messages can be sent to/from Discord through DiscordSRV.

**Comment by mbax** [comment]
What happens if there are more than 500 towns with towny integration?

**Comment by partydev** [comment]
I do not think that DiscordSRV support is necessary for Towny channels. Plugins that are similar do not offer it (VentureChat does not let you do both Discord and Towny).

It would just open up a can of worms. I think that it should just be limited to channels that are not integrated with other plugins.
