### ISSUE TITLE
JSON Hover Formatting

### ISSUE THREAD

**Issue by partydev** [egg82/TabChat#4]
**Describe the solution you'd like**
Ability to configure sections of the username, prefix, chat, suffix, etc. to display a message when hovered over with a mouse. Additionally, a command to be run (or filled into chat) when a user clicks on the formatted section. Possibility of clicking on a username to initiate a private conversation.

**Additional Context**
Example:
![image](https://user-images.githubusercontent.com/42015460/74970665-c45c6c00-53ec-11ea-82b2-68147b79ec3b.png)

**Comment by clrxbl** [comment]
Would also be nice to have a user-friendly way of adding these messages (e.g. - "%placeholder% test") instead of raw JSON
