### ISSUE TITLE
Ignore Other Players

### ISSUE THREAD

**Issue by partydev** [egg82/TabChat#5]
**Describe the solution you'd like**
Ability to use /ignore on a player. This will hide any messages sent by the ignored player from appearing in any channel. Additionally, prevent that user from initiating a private conversation with you.

**Comment by clrxbl** [comment]
"Additionally, prevent that user from initiating a private conversation with you."

This feature should be configurable, whether to simply block the message from being sent or to let it send but make it so the other user doesn't see it.
